name: "Setup"
description: "Install pnpm and Node.js"
runs:
  using: "composite"
  steps:
    # Error: Bad request - pnpm/action-setup@v4 is not allowed to be used in userfront/userfront. Actions in this workflow must be: within a repository owned by userfront, created by GitHub, verified in the GitHub Marketplace, or matching the following: changesets/action@v1.
    # - uses: pnpm/action-setup@v4
    #   name: Install pnpm
    #   with:
    #     version: 10
    #     run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23
        # cache: "pnpm"
    - name: Install pnpm
      run: npm i pnpm@latest -g
      shell: bash
    - name: Install dependencies
      run: pnpm install
      shell: bash
