packages:
    # example applications
    - "apps/*"
    # distributable packages
    - "packages/*"
    # non-distributable packages, development dependencies
    - 'internals/*'
    # exclude packages that are inside test directories
    - "!**/test/**"
