name: "Checks"
runs:
  using: "composite"
  steps:
    - name: Lint
      run: pnpm run lint

    - name: Unit tests
      run: pnpm test

    - name: Check types
      run: pnpm run check-types

    - name: Build
      run: pnpm run build
