name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Setup Node.js 21.x
      uses: actions/setup-node@v3
      with:
        node-version: 21.x

    - name: Install pnpm
      run: npm i pnpm@latest -g

    - name: Setup pnpm config
      run: pnpm config set store-dir $PNPM_CACHE_FOLDER

    - name: Install dependencies
      run: pnpm install
