name: "Checks"
description: "Run lint, build, type check and unit tests"

runs:
  using: "composite"
  steps:
    - name: Lint
      run: pnpm run lint
      shell: bash

    - name: Build
      run: pnpm run build
      shell: bash

    - name: Check types
      run: pnpm run check-types
      shell: bash

    - name: Checks for known security issues with the installed packages
      run: pnpm audit --audit-level=high
      shell: bash

    - name: Unit tests
      run: pnpm run test
      shell: bash
