import type { Metadata } from "next";
import { UserfrontProvider } from "@userfront/next/client";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserfrontProvider
          tenantId={process.env.NEXT_PUBLIC_USERFRONT_TENANT_ID ?? ""}
        >
          {children}
        </UserfrontProvider>
      </body>
    </html>
  );
}
