name: PR CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read #  to fetch code (actions/checkout)

env:
  CI: true

jobs:
  build:
    name: Build
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: ./.github/actions/checks
